### ISSUE TITLE
Cannot deploy

### ISSUE THREAD

**Issue by oddbyte** [titaniumnetwork-dev/Alu#26]
Getting this error:
```
root@oddbyte:/home/proxy/Alu# pnpm start

> alus-unblocker@0.0.1 start /home/proxy/Alu
> node .

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1171:7)
    at file:///home/proxy/Alu/node_modules/@rubynetwork/rh/src/config.js:15:21
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.20.3
 ELIFECYCLE  Command failed with exit code 1.
```

Full terminal log:
```
root@oddbyte:/home/proxy# git clone https://github.com/titaniumnetwork-dev/Alu --recurse-submodules
Cloning into 'Alu'...
remote: Enumerating objects: 3323, done.
remote: Counting objects: 100% (1749/1749), done.
remote: Compressing objects: 100% (562/562), done.
remote: Total 3323 (delta 1184), reused 1640 (delta 1108), pack-reused 1574 (from 1)
Receiving objects: 100% (3323/3323), 3.50 MiB | 4.22 MiB/s, done.
Resolving deltas: 100% (2087/2087), done.
Submodule 'public/games' (https://github.com/wearrrrr/alu-games) registered for path 'public/games'
Cloning into '/home/proxy/Alu/public/games'...
remote: Enumerating objects: 6541, done.        
remote: Counting objects: 100% (768/768), done.        
remote: Compressing objects: 100% (701/701), done.        
remote: Total 6541 (delta 60), reused 756 (delta 49), pack-reused 5773 (from 1)        
Receiving objects: 100% (6541/6541), 1.64 GiB | 5.49 MiB/s, done.
Resolving deltas: 100% (328/328), done.
Submodule path 'public/games': checked out '3b028f45966cc75fc1fd73e92d78f7eb0d7cfcba'
root@oddbyte:/home/proxy# 
root@oddbyte:/home/proxy# ls
Alu  Ultraviolet-App
root@oddbyte:/home/proxy# cd Alu
root@oddbyte:/home/proxy/Alu# npm i -g pnpm

changed 1 package in 6s

1 package is looking for funding
  run `npm fund` for details
root@oddbyte:/home/proxy/Alu# pnpm i
Lockfile is up to date, resolution step is skipped
Packages: +742
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 742, reused 742, downloaded 0, added 742, done

dependencies:
+ @astrojs/node 8.3.4
+ @inox-tools/sitemap-ext 0.3.3
+ @mercuryworkshop/bare-as-module3 2.2.2
+ @mercuryworkshop/bare-mux 2.0.9
+ @mercuryworkshop/epoxy-transport 2.1.11
+ @mercuryworkshop/libcurl-transport 1.3.10
+ @rubynetwork/rammerhead 1.3.2
+ @titaniumnetwork-dev/ultraviolet 3.2.7
+ @tomphttp/bare-server-node 2.0.4
+ @types/node 20.16.9
+ astro 4.15.9
+ chalk 5.3.0
+ cookie-parser 1.4.6
+ dotenv-flow 4.1.0
+ express 4.21.0
+ notyf 3.10.0
+ sequelize 6.37.3
+ sqlite3 5.1.7
+ wisp-server-node 1.1.7

optionalDependencies:
+ bufferutil 4.0.8

devDependencies:
+ @typescript-eslint/eslint-plugin 7.18.0
+ @typescript-eslint/parser 7.18.0
+ eslint 8.57.1
+ eslint-plugin-astro 0.31.4
+ prettier 3.2.5
+ prettier-plugin-astro 0.13.0

Done in 6.2s
root@oddbyte:/home/proxy/Alu# pnpm build

> alus-unblocker@0.0.1 build /home/proxy/Alu
> astro build

▶ Astro collects anonymous usage data.
  This information helps us improve Astro.
  Run "astro telemetry disable" to opt-out.
  https://astro.build/telemetry

17:42:38 [WARN] [config] The adapter @astrojs/node provides experimental support for "astro:env getSecret". You may experience issues or breaking changes until this feature is fully supported by the adapter.
17:42:38 [types] Generated 377ms
17:42:38 [build] output: "server"
17:42:38 [build] directory: /home/proxy/Alu/dist/
17:42:38 [build] adapter: @astrojs/node
17:42:38 [build] Collecting build info...
17:42:38 [build] ✓ Completed in 434ms.
17:42:38 [build] Building server entrypoints...
17:42:43 [vite] ✓ built in 4.89s
17:42:43 [build] ✓ Completed in 5.09s.

 building client (vite) 
17:42:44 [vite] ✓ 42 modules transformed.
17:43:04 [vite] dist/client/_astro/notyf.CV79g7kv.css     5.12 kB │ gzip: 1.21 kB
17:43:04 [vite] dist/client/_astro/hoisted.DeBiR4Od.js    0.50 kB │ gzip: 0.24 kB
17:43:04 [vite] dist/client/_astro/hoisted.CRRNv7nf.js    0.58 kB │ gzip: 0.35 kB
17:43:04 [vite] dist/client/_astro/hoisted.CGtfU7SP.js    0.64 kB │ gzip: 0.28 kB
17:43:04 [vite] dist/client/_astro/Alu.C12DOZhB.js        1.02 kB │ gzip: 0.49 kB
17:43:04 [vite] dist/client/_astro/hoisted.DTYnFHYV.js    5.31 kB │ gzip: 1.86 kB
17:43:04 [vite] dist/client/_astro/hoisted.Bblim_2X.js    6.12 kB │ gzip: 1.89 kB
17:43:04 [vite] dist/client/_astro/notyf.es.aI0yz9tx.js   8.60 kB │ gzip: 2.95 kB
17:43:04 [vite] dist/client/_astro/hoisted.CosvxsE_.js   13.78 kB │ gzip: 4.62 kB
17:43:04 [vite] dist/client/_astro/hoisted.CNjsbFoB.js   17.73 kB │ gzip: 5.99 kB
17:43:04 [vite] ✓ built in 21.00s

 prerendering static routes 
17:43:05 ▶ src/pages/[lang]/games.astro
17:43:05   ├─ /en/games/index.html (+152ms)
17:43:05   ├─ /es/games/index.html (+68ms)
17:43:05   ├─ /fr/games/index.html (+48ms)
17:43:05   ├─ /jp/games/index.html (+51ms)
17:43:05   ├─ /pt/games/index.html (+45ms)
17:43:05   ├─ /ru/games/index.html (+42ms)
17:43:05   └─ /zh/games/index.html (+43ms)
17:43:05 ▶ src/pages/[lang]/marketplace.astro
17:43:05   ├─ /en/marketplace/index.html (+16ms)
17:43:05   ├─ /es/marketplace/index.html (+15ms)
17:43:05   ├─ /fr/marketplace/index.html (+14ms)
17:43:05   ├─ /jp/marketplace/index.html (+13ms)
17:43:05   ├─ /pt/marketplace/index.html (+11ms)
17:43:05   ├─ /ru/marketplace/index.html (+11ms)
17:43:05   └─ /zh/marketplace/index.html (+14ms)
17:43:05 ▶ src/pages/[lang]/settings.astro
17:43:05   ├─ /en/settings/index.html (+24ms)
17:43:05   ├─ /es/settings/index.html (+20ms)
17:43:05   ├─ /fr/settings/index.html (+18ms)
17:43:05   ├─ /jp/settings/index.html (+19ms)
17:43:05   ├─ /pt/settings/index.html (+18ms)
17:43:05   ├─ /ru/settings/index.html (+17ms)
17:43:05   └─ /zh/settings/index.html (+17ms)
17:43:05 ▶ src/pages/[lang]/index.astro
17:43:05   ├─ /en/index.html (+10ms)
17:43:05   ├─ /es/index.html (+8ms)
17:43:05   ├─ /fr/index.html (+8ms)
17:43:05   ├─ /jp/index.html (+11ms)
17:43:05   ├─ /pt/index.html (+9ms)
17:43:05   ├─ /ru/index.html (+8ms)
17:43:05   └─ /zh/index.html (+8ms)
17:43:05 ✓ Completed in 815ms.

17:43:05 
 finalizing server assets 

17:43:05 [build] Rearranging server assets...
17:43:06 [@astrojs/sitemap] `sitemap-index.xml` created at `dist/client`
17:43:06 [build] Server built in 27.94s
17:43:06 [build] Complete!
root@oddbyte:/home/proxy/Alu# pnpm start

> alus-unblocker@0.0.1 start /home/proxy/Alu
> node .

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1171:7)
    at file:///home/proxy/Alu/node_modules/.pnpm/@rubynetwork+rh@1.2.71_bufferutil@4.0.8_utf-8-validate@6.0.4/node_modules/@rubynetwork/rh/src/config.js:15:21
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.20.3
 ELIFECYCLE  Command failed with exit code 1.
root@oddbyte:/home/proxy/Alu# npm i
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm warn deprecated gauge@4.0.4: This package is no longer supported.

added 741 packages, changed 40 packages, and audited 782 packages in 47s

224 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
root@oddbyte:/home/proxy/Alu# pnpm start

> alus-unblocker@0.0.1 start /home/proxy/Alu
> node .

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1171:7)
    at file:///home/proxy/Alu/node_modules/@rubynetwork/rh/src/config.js:15:21
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.20.3
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by wearrrrr** [comment]
Please upgrade to Node 20 :)
If that doesn't work, this seems to be an issue with https://www.npmjs.com/package/@rubynetwork/rh, I would suggest opening an issue there.

**Comment by oddbyte** [comment]
Upgrading to node 20 fixed it. Thanks!
